#!/usr/bin/env python3
"""
Turns a county workbook into assets/data/<slug>.js.

  python3 tools/import_county.py Thomas_County_Info.xlsx thomas

The workbook needs one sheet whose name contains "Industry", laid out in
columns, with row 2 carrying the headings:

  A  Largest Industries        one cell per industry, blank on continuation rows
  B  Local Companies in That Industry
  C  High School Pathways (District Name)
  D  <University Name> Majors
  E  <Technical College Name>

Everything below an industry's name, down to the next industry, belongs to it.
The institution for each of the last three columns is read out of its own
heading, so a workbook for another county needs no code changes.

In column C, a cell ending in "Pathway:" starts a pathway and the cells under
it are its courses.

A second sheet whose name contains "Education" is read the same way — a
district name in column A, the pathways it offers in column B — and becomes
the county-wide list of CTAE pathways by district shown under the cards.

Blurbs, images and captions already written into the data file are kept — this
only replaces companies and program lists, so re-importing an updated workbook
never costs you hand-written copy.
"""
import json, os, re, sys

try:
    import openpyxl
except ImportError:
    sys.exit("openpyxl is needed: pip install openpyxl")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AWARDS = r"TCC|AAS|AS|AA|BS|BA|Diploma|Certificate"

HEADER = '''/* {county} County — target industries and aligned education programs.
 *
 * Generated by tools/import_county.py from {source}
 * Hand-edited blurbs, images and captions are preserved across re-imports.
 *
 * Each industry takes:
 *   id         short slug, used in the page address (#industry-health-care)
 *   name       what the card and the detail view are titled
 *   blurb      one sentence on why this industry matters here
 *   companies  a list of local employers. The card shows how many.
 *   programs   optional. Left out, the card counts the three program lists.
 *   image      path to a photo, e.g. "../assets/img/industries/{slug}-health-care.jpg"
 *              Leave it null and a labelled empty frame shows instead.
 *   imageCaption  optional line printed under the image
 *   ctae       high school CTAE pathways, each with optional courses
 *   technical  technical college programs
 *   university university programs offered in this county
 *
 * Every program takes: name, org, and optionally award, courses and url.
 */
window.PATHWAY_DATA = '''


MINOR = "and or of the in at for to with a an"

# Acronyms that stay in capitals when a shouting line is recased.
# Add to this list if a workbook uses one this does not know about.
ACRONYMS = {"SRTC", "CTAE", "CNC", "CAD", "CTE", "EMS", "EMT", "HVAC", "STEM",
            "JROTC", "AAS", "TCC", "LPN", "BSN", "MBA", "IT", "GED", "OSHA"}


def tidy(name):
    """Source sheets shout some names in capitals; the page does not.

    A line is only recased if something in it is genuinely shouting, so
    ordinary program names pass through untouched."""
    if not re.search(r"\b[A-Z]{5,}\b", name):
        return name

    def recase(m):
        w = m.group(0)
        return w if w in ACRONYMS else w.capitalize()

    out = re.sub(r"\b[A-Z]{3,}\b", recase, name)
    minor = r"(?<!^)\b(?:%s)\b" % "|".join(
        w.capitalize() for w in MINOR.split())
    return re.sub(minor, lambda m: m.group(0).lower(), out)


def dedupe(items, key):
    seen, out = set(), []
    for it in items:
        k = key(it)
        if k not in seen:
            seen.add(k)
            out.append(it)
    return out


def slugify(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def org_from_heading(text, strip_words=()):
    """Institution names live in the column headings."""
    text = re.sub(r"\s+", " ", (text or "")).strip()
    paren = re.search(r"\(([^)]+)\)", text)
    if paren:
        return paren.group(1).strip()
    for w in strip_words:
        text = re.sub(w, "", text, flags=re.I).strip()
    return text.strip(" -–—")


def parse_award(text):
    """'Automation Technology, AAS (IS13) / Diploma (IST4)' ->
       ('Automation Technology', 'AAS · IS13 / Diploma · IST4')

    A fragment after ' / ' that starts with an award is another award for the
    same program; anything else is a separate program, so it is handed back
    to the caller as an extra entry."""
    extras = []
    parts = [p.strip() for p in text.split(" / ")]
    head, tail = parts[0], []
    for p in parts[1:]:
        if re.match(r"^(?:%s)\b" % AWARDS, p, flags=re.I):
            tail.append(p)
        else:
            extras.append(p)

    m = re.match(r"^(?P<name>.*?),\s*(?P<award>%s)\s*\((?P<code>[^)]*)\)\s*$" % AWARDS,
                 head, flags=re.I)
    if m:
        name = m.group("name").strip()
        awards = ["%s · %s" % (m.group("award"), m.group("code"))]
    else:
        m2 = re.match(r"^(?P<name>.*?),\s*\((?P<code>[^)]*)\)\s*$", head)
        if m2:
            name, awards = m2.group("name").strip(), [m2.group("code")]
        else:
            name, awards = head, []

    for t in tail:
        m3 = re.match(r"^(?P<award>%s)\s*\((?P<code>[^)]*)\)\s*$" % AWARDS, t, flags=re.I)
        awards.append("%s · %s" % (m3.group("award"), m3.group("code")) if m3 else t)

    return name, (" / ".join(awards) or None), extras


def build_ctae(rows, org):
    """A cell ending in 'Pathway:' opens a pathway; the cells under it are
    its courses. A cell with no pathway open is a pathway on its own."""
    out = []
    for text in rows:
        if text.endswith(":"):
            out.append({"name": tidy(text.rstrip(": ").strip()), "org": org, "courses": []})
        elif out and out[-1]["courses"] is not None and out[-1].get("_open"):
            out[-1]["courses"].append(text)
        elif out and out[-1].get("_open"):
            out[-1]["courses"].append(text)
        else:
            out.append({"name": tidy(text), "org": org, "courses": []})
        if text.endswith(":"):
            out[-1]["_open"] = True
    for p in out:
        p.pop("_open", None)
        if not p["courses"]:
            del p["courses"]
    return out


def sheet_rows(wb, word, width):
    sheet = next((ws for ws in wb.worksheets if word in ws.title.lower()), None)
    if sheet is None:
        return None
    rows = [[("" if c is None else str(c).strip()) for c in r]
            for r in sheet.iter_rows(values_only=True)]
    return [r + [""] * (width - len(r)) for r in rows]


def read_districts(wb):
    """Column A names a district, column B lists what it offers."""
    rows = sheet_rows(wb, "education", 2)
    if not rows:
        return []
    blocks = []
    for row in rows:
        if row[0]:
            blocks.append({"name": row[0], "raw": []})
        if blocks and row[1]:
            blocks[-1]["raw"].append(row[1])
    out = []
    for b in blocks:
        if not b["raw"]:          # a heading with nothing under it
            continue
        out.append({"name": b["name"], "pathways": build_ctae(b["raw"], b["name"])})
    for d in out:
        for p in d["pathways"]:
            p.pop("org", None)
    return out


def read_industries(path):
    wb = openpyxl.load_workbook(path, data_only=True)
    rows = sheet_rows(wb, "industr", 5)
    if rows is None:
        sys.exit("no sheet with 'Industry' in its name")

    head = rows[1]
    orgs = {
        "ctae": org_from_heading(head[2]) or "High school",
        "university": org_from_heading(head[3], (r"\bMajors\b",)),
        "technical": org_from_heading(head[4]),
    }

    blocks = []
    for row in rows[2:]:
        if row[0]:
            blocks.append({"name": row[0], "companies": [], "ctae": [],
                           "university": [], "technical": []})
        if not blocks:
            continue
        b = blocks[-1]
        if row[1]:
            b["companies"].append(row[1])
        if row[2]:
            b["ctae"].append(row[2])
        if row[3]:
            b["university"].append(row[3])
        if row[4]:
            b["technical"].append(row[4])
    return blocks, orgs, read_districts(wb)


def to_industry(block, orgs):
    name = block["name"]

    # The company column repeats an employer that has more than one site.
    companies = dedupe(block["companies"], lambda c: c.lower())

    technical = []
    for text in block["technical"]:
        if text.lower() == name.lower():      # a category label, not a program
            continue
        pname, award, extras = parse_award(text)
        entry = {"name": tidy(pname), "org": orgs["technical"]}
        if award:
            entry["award"] = award
        technical.append(entry)
        for extra in extras:
            ename, eaward, _ = parse_award(extra)
            e = {"name": tidy(ename), "org": orgs["technical"]}
            if eaward:
                e["award"] = eaward
            technical.append(e)

    return {
        "id": slugify(name),
        "name": name,
        "blurb": "",
        "companies": companies,
        "image": None,
        "ctae": build_ctae(block["ctae"], orgs["ctae"]),
        "technical": dedupe(technical, lambda t: (t["name"], t.get("award"))),
        "university": dedupe(
            [{"name": tidy(u), "org": orgs["university"]} for u in block["university"]],
            lambda u: u["name"]),
    }


def keep_handwritten(industries, slug):
    """Carry blurb / image / imageCaption over from the existing data file."""
    path = os.path.join(ROOT, "assets", "data", slug + ".js")
    if not os.path.exists(path):
        return
    text = open(path).read()
    m = re.search(r"window\.PATHWAY_DATA\s*=\s*(\{.*\});?\s*$", text, re.S)
    if not m:
        return
    try:
        old = json.loads(m.group(1))
    except ValueError:
        return
    by_id = {i.get("id"): i for i in old.get("industries", [])}
    for ind in industries:
        prev = by_id.get(ind["id"])
        if not prev:
            continue
        for field in ("blurb", "image", "imageCaption"):
            if prev.get(field):
                ind[field] = prev[field]


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__.strip())
    path, slug = sys.argv[1], sys.argv[2]
    county = sys.argv[3] if len(sys.argv) > 3 else slug.title()

    blocks, orgs, districts = read_industries(path)
    industries = [to_industry(b, orgs) for b in blocks]
    keep_handwritten(industries, slug)

    data = {"slug": slug, "county": county, "sample": False,
            "industries": industries, "districts": districts}
    out = os.path.join(ROOT, "assets", "data", slug + ".js")
    with open(out, "w") as fh:
        fh.write(HEADER.format(county=county, slug=slug, source=os.path.basename(path)) +
                 json.dumps(data, indent=2, ensure_ascii=False) + ";\n")

    print("institutions:", orgs)
    print("wrote", os.path.relpath(out, ROOT))
    for i in industries:
        print("  %-42s %3d companies  %2d CTAE  %2d tech  %2d university"
              % (i["name"], len(i["companies"]), len(i["ctae"]),
                 len(i["technical"]), len(i["university"])))
    for d in districts:
        print("  district: %-32s %2d pathways" % (d["name"], len(d["pathways"])))


if __name__ == "__main__":
    main()
